### ISSUE TITLE
EOF during handshake

### ISSUE THREAD

**Issue by blarney2000** [rocketlaunchr/https-go#1]
I get the following console error message when loading a page locally from https://localhost:8080:

http: TLS handshake error from [::1]:52080: EOF

Sometimes it's this error instead:
 http: TLS handshake error from [::1]:61288: remote error: tls: unknown certificate

**Comment by pjebs** [comment]
Can you show me your code?

**Comment by pjebs** [comment]
Are you also allowing self signed certificates? How are you making the http request? From a browser?

**Comment by blarney2000** [comment]
My code: 
package main

import (
	"fmt"
	"log"
	"net/http"
	"github.com/rocketlaunchr/https-go"
)

func main() {
	http.HandleFunc("/", func(res http.ResponseWriter, req *http.Request) {
		fmt.Fprint(res, "Hello World!")
	})

	httpServer, _ := https.Server("8080", https.GenerateOptions{Host: "localhost"})
	log.Fatal(httpServer.ListenAndServeTLS("", ""))
}

//error: http: TLS handshake error from [::1]:61064: remote error: tls: unknown certificate

**Comment by pjebs** [comment]
Are you reaching the end point through the browser. If so, your browser won't by default trust your certificate (since it's self signed). 

You need to add it as an allowed exception.

**Comment by pjebs** [comment]
Closing if no more information.
